# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Biosketch"
  url = "biosketch"
  weight = 30


[[main]]
  name = "Projects"
  url = "#projects"
  weight = 50

[[main]]
  name = "Research"
  url = "research/"
  weight = 70


[[main]]
  name = "Publications"
  url = "publications"
  weight = 90
  

  
[[main]]
  name = "Math Book"
  url = "mathbook/"
  weight = 110

[[main]]
  name = "Finance Book"
  url = "financebook/"
  weight = 130

[[main]]
  name = "Finance Book"
  url = "financebook/"
  weight = 150

[[main]]
  name = "Misc"
  url = "misc"
  weight = 170


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
